### ISSUE TITLE
Could you please add unit tests?

### ISSUE THREAD

**Issue by yesudeep** [eyalz800/maybe#1]
Having some unit tests would be good. What do you think?

**Comment by eyalz800** [comment]
The tests I did was running the manual example in the readme, I am using this utility in various projects and because it's working and so little logic, I did not want to deploy any further tests. I also looked at the assembly generated in various cases to verify that I did not make the compiler do any extra than it should have. @yesudeep

**Comment by yesudeep** [comment]
The rationale is pretty simple I think. It allows users of the library to ensure their code 
continues to work if the library changes. 

For example, I import the library using Bazel and would prefer to include its unit tests 
within my test suites as well. Therefore, if the library receives an update that changes functionality, 
the tests would catch it. It makes the library more dependable. 

I'm certain the code is pretty small but even a small piece of code can have unintended consequences
beyond its original purpose. Would you agree? Still it's entirely up to you to decide whether
it makes sense to include tests. Please feel free to close the bug. :)

**Comment by eyalz800** [comment]
Yes I agree, I wish I had time to write tests though

**Comment by yesudeep** [comment]
I turned your examples into tests locally. But they use googletest and bazel. Would you be willing to accept PRs?

**Comment by eyalz800** [comment]
@yesudeep I got a notification in the email that you're willing to have a PR about some tests, I don't see the comment here, but I can accept it - please put all the tests in a subdirectory named tests. @yesudeep
